Repository HarshwardhanPatil07/HactoberFest2025, pull requests merged in 2023-10, with the labels that each got.

#2 C++ contribution
  C++ (MATRIX)/2DArrayArguments.cpp
  C++ (MATRIX)/MatrixSnake.cpp
  C++ (MATRIX)/medianOfRowWiseSortedMatrix.cpp
  C++ (MATRIX)/multiDimenisonalArray.cpp
  C++ (MATRIX)/printBoundaryElements.cpp
  C++ (MATRIX)/rotate90.cpp
  C++ (MATRIX)/searchInSortedMatrix.cpp
  C++ (MATRIX)/sprialMatrix.cpp
  C++ (MATRIX)/transposeOfMatrix.cpp
  CONTRIBUTORS.md
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2023

#5 Added DFS_BFS.c Menu driven
  CONTRIBUTORS.md
  c/DFS_BFS_MenuDriven.c
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2023

#8 CircularDoublyLinkedList
  CircularDoublyLinkedList
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2023

#10 Spiral order of matrix
  CONTRIBUTORS.md
  c++/C++ (MATRIX)/matrixInSpiralOrder.cpp
  c++/C++ (MATRIX)/tempCodeRunnerFile.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2023

#24 Create checksum.cpp
  c++/checksum.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2023

#27 added Radix Sort
  .vscode/settings.json
  Python/Sorting.py
  c/duplicatesInArray.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#29 Create Bank_Management_Systum.cpp
  c++/Bank_Management_Systum.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#34 Contribution
  CONTRIBUTORS.md
  c++/Factorial.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#38 Feat/pattern
  c++/Floyd's_triangle.cpp
  c++/Inverted_halfPyramidNum.cpp
  c++/Pascal_triangle.cpp
  c++/Triangle.cpp
  c++/half-pyramidAlpha.cpp
  c++/half_pyramid.cpp
  c++/half_pyramidNum.cpp
  c++/inverted_halfPyramid.cpp
  c++/inverted_triangle.cpp
  c++/triangleNum.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#42 compile issues
  c++/scene-graph.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#43 box2d-platform-example.cpp
  c++/box2d-platform-example.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#54 Created a snake game.py
  Python/Created a snake game.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#52 Draw a graph paper.py
  Python/Draw a rainbow
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#66 Added Email client code in Python
  Python/mail.py
  Python/mail.ui
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#78 added best fit algorithm
  CONTRIBUTORS.md
  JavaScript/bestFitAlgorithm/.gitignore
  JavaScript/bestFitAlgorithm/bestFitAlgorithm.js
  JavaScript/bestFitAlgorithm/package-lock.json
  JavaScript/bestFitAlgorithm/package.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#61 Scientific Calculator
  c++/Calculator.cpp
  c++/GuessTheNumber.cpp
Labels: good first issue

#84 Create concentric_circles.cpp
  c++/concentric_circles.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#87 Create Bank Managing System.py
  Bank Managing System
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#95 data structure in c
  AVL_tree.c
  B+_tree.c
  B_tree.c
  c/AVL_tree.c
  c/B+_tree.c
  c/BFS_adjacency_list.c
  c/BFS_adjacency_matrix.c
  c/BST_tree.c
  c/B_tree.c
  c/Binary_tree_operation.c
  c/DFS_&_BFS_together.c
  c/DFS_adjacency_list.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#101 Create a ping pong game.c
  c/ping pong.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023
